name: Limpiar Base de Datos de Usuarios

on:
  workflow_dispatch: {}

jobs:
  clear-users:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # 2. Eliminar todos los archivos excepto `users.json`
      - name: Eliminar contenido excepto `users.json`
        run: |
          cd Usuarios
          # Preservar `users.json` y eliminar todo lo demás
          find . -type f ! -name "users.json" -delete
          find . -type d ! -path "." -exec rm -rf {} +

      # 3. Limpiar el archivo `users.json`
      - name: Limpiar archivo de usuarios
        run: |
          echo '{"users":[]}' > Usuarios/users.json

      # 4. Hacer commit y push de los cambios
      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Agregar los cambios al repositorio
          git add .
          git commit -m "Limpiar base de datos de usuarios, preservando users.json"
          git push
