name: Limpiar Base de Datos de Libros

on:
  workflow_dispatch: {}

jobs:
  clear-books:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # 2. Limpiar los archivos de libros
      - name: Limpiar archivos de libros
        run: |
          echo '{"books":[]}' > Libros/pendientes.json
          echo '{"books":[]}' > Libros/en_lectura.json
          echo '{"books":[]}' > Libros/acabados.json
          echo '{"books":[]}' > Libros/favoritos.json

      # 3. Eliminar el archivo README.md de la carpeta Libros
      - name: Eliminar README.md
        run: |
          rm -f Libros/README.md
          git rm -f Libros/README.md  # Asegurarse de que Git registre la eliminaci칩n

      # 4. Hacer commit y push de los cambios
      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # A침adir los archivos modificados a la etapa de commit
          git add Libros/pendientes.json Libros/en_lectura.json Libros/acabados.json Libros/favoritos.json

          # Generar el mensaje de commit din치micamente
          commit_message="Limpiar base de datos de libros y eliminar README.md"
          git commit -m "$commit_message"

          # Realizar el push con el token de autenticaci칩n
          git push

