name: Limpiar Base de Datos de Usuarios

on:
  workflow_dispatch: {}

jobs:
  clear-users:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # 2. Limpiar el archivo de usuarios
      - name: Limpiar archivo de usuarios
        run: |
          echo '{"users":[]}' > users.json

      # 3. Hacer commit y push de los cambios
      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add users.json
          git commit -m "Limpiar base de datos de usuarios"
          git push
