name: Limpiar Base de Datos de Libros

on:
  workflow_dispatch: {}

jobs:
  clear-books:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # 2. Limpiar los archivos de libros
      - name: Limpiar archivos de libros
        run: |
          echo '{"books":[]}' > Libros/pendientes.json
          echo '{"books":[]}' > Libros/en_lectura.json
          echo '{"books":[]}' > Libros/acabados.json
          echo '{"books":[]}' > Libros/favoritos.json

      # 3. Hacer commit y push de los cambios
      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Libros/pendientes.json Libros/en_lectura.json Libros/acabados.json Libros/favoritos.json
          git commit -m "Limpiar base de datos de libros"
          git push
