name: Organizar Biblioteca por Tipo

on:
  push:
    paths:
      - 'Biblioteca/biblioteca.json'

jobs:
  organize-library:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # 2. Validar biblioteca.json
      - name: Validar biblioteca.json
        run: |
          BIBLIOTECA_JSON="Biblioteca/biblioteca.json"

          # Verificar que el archivo JSON es v치lido
          jq empty "$BIBLIOTECA_JSON" || { echo "Error: El archivo biblioteca.json tiene un formato inv치lido."; exit 1; }

      # 3. Leer y procesar biblioteca.json
      - name: Procesar biblioteca.json
        run: |
          # Definir ruta al archivo JSON
          BIBLIOTECA_JSON="Biblioteca/biblioteca.json"

          # Leer los tipos 칰nicos y procesar libros
          types=$(jq -r '.books[].type' "$BIBLIOTECA_JSON" | sort | uniq)
          for type in $types; do
            # Crear carpeta para cada tipo si no existe
            type_dir="Libros/$type"
            mkdir -p "$type_dir"

            # Ruta al README.md dentro de la carpeta
            readme="$type_dir/README.md"

            # Crear README.md si no existe
            if [ ! -f "$readme" ]; then
              echo "# 游닄 Libros de $type" > "$readme"
              echo "Bienvenido a la colecci칩n de libros de **$type**. Aqu칤 encontrar치s los libros clasificados por este g칠nero." >> "$readme"
              echo "---" >> "$readme"
              echo "" >> "$readme"
            fi

            # A침adir libros al README.md
            books=$(jq -c ".books[] | select(.type==\"$type\")" "$BIBLIOTECA_JSON")
            for book in $books; do
              title=$(echo "$book" | jq -r '.title')
              author=$(echo "$book" | jq -r '.author')
              status=$(echo "$book" | jq -r '.status')
              favorite=$(echo "$book" | jq -r '.favorite')

              # Verificar si el libro ya est치 en el README
              if ! grep -q "## $title" "$readme"; then
                echo "## $title" >> "$readme"
                echo "- **Autor**: $author" >> "$readme"
                echo "- **Estado**: $status" >> "$readme"
                echo "- **Favorito**: $favorite" >> "$readme"
                echo "" >> "$readme"
                echo "### Comentarios" >> "$readme"
                echo "> A침ade aqu칤 tus comentarios sobre este libro." >> "$readme"
                echo "---" >> "$readme"
                echo "" >> "$readme"
              fi
            done
          done

      # 4. Hacer commit y push de los cambios
      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Libros/
          git commit -m "Organizar biblioteca por tipo y actualizar README.md de libros" || echo "No hay cambios para commitear."
          git push
